name: git2gitee
on:
  push:
    branches:
      - master
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github repos to Gitee.
      uses: wxzed/hub-mirror-action@master
      with:
        src: 'github/${{ github.repository_owner }}'
        dst: 'gitee/${{ secrets.GITEE_USER }}'
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        static_list: ${{ github.event.repository.name }}
        force_update: true
